"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { Show, SignUp, useUser } from "@clerk/nextjs";
import { MaturaLogo } from "@/components/MaturaLogo";

const FEATURES = [
  {
    icon: "\u2728",
    title: "Idea to Plan in Minutes",
    description:
      "Describe your software idea in plain language and get a complete, implementation-ready plan generated by AI agents.",
  },
  {
    icon: "\u{1F501}",
    title: "Retro-Feedback Loop",
    description:
      "Refine any artifact and watch changes propagate automatically across vision, requirements, architecture, and backlog.",
  },
  {
    icon: "\u{1F4CA}",
    title: "Business & Technical Views",
    description:
      "One pipeline, two dashboards. Business stakeholders see cost and competitive analysis. Engineers see architecture and tests.",
  },
  {
    icon: "\u{1F3D7}\uFE0F",
    title: "Full SDLC Coverage",
    description:
      "Vision, requirements, architecture, frameworks, backlog, test definitions, cost estimates, and competitive analysis.",
  },
];

export default function Home() {
  const router = useRouter();
  const { isSignedIn, isLoaded } = useUser();

  useEffect(() => {
    if (isLoaded && isSignedIn) {
      router.replace("/home");
    }
  }, [isLoaded, isSignedIn, router]);

  if (!isLoaded) return null;

  return (
    <Show when="signed-out">
      <div className="min-h-screen bg-background">
        {/* Header */}
        <header className="border-b border-border bg-nav-bg">
          <div className="mx-auto flex h-14 max-w-6xl items-center px-4 sm:px-6">
            <MaturaLogo className="h-7" />
          </div>
        </header>

        {/* Hero */}
        <div className="mx-auto max-w-6xl px-4 sm:px-6 py-12 lg:py-20">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-start">
            {/* Left: copy + features */}
            <div className="flex flex-col gap-8">
              <div>
                <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-foreground leading-tight">
                  From rough idea to<br />implementation-ready plan
                </h1>
                <p className="mt-4 text-lg text-foreground-secondary leading-relaxed max-w-lg">
                  matura is an agentic AI system that transforms a software concept into a
                  complete SDLC specification — vision, requirements, architecture, backlog,
                  tests, and more — in minutes, not weeks.
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                {FEATURES.map((f) => (
                  <div
                    key={f.title}
                    className="rounded-xl border border-border bg-card-bg p-4"
                  >
                    <span className="text-xl">{f.icon}</span>
                    <h3 className="mt-2 text-sm font-semibold text-foreground">
                      {f.title}
                    </h3>
                    <p className="mt-1 text-xs text-foreground-secondary leading-relaxed">
                      {f.description}
                    </p>
                  </div>
                ))}
              </div>

              <p className="text-xs text-foreground-muted">
                Built for the Swiss Life Claude Builders Hackathon. Powered by Claude.
              </p>
            </div>

            {/* Right: Clerk SignUp */}
            <div className="flex justify-center lg:justify-end">
              <SignUp routing="hash" />
            </div>
          </div>
        </div>
      </div>
    </Show>
  );
}
